//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YapayAntenor.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TEZEntities : DbContext
    {
        public TEZEntities()
            : base("name=TEZEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Admin> TBL_Admin { get; set; }
        public virtual DbSet<TBL_Bacak> TBL_Bacak { get; set; }
        public virtual DbSet<TBL_Beslenme> TBL_Beslenme { get; set; }
        public virtual DbSet<TBL_Blog> TBL_Blog { get; set; }
        public virtual DbSet<TBL_Gogus> TBL_Gogus { get; set; }
        public virtual DbSet<TBL_Hakkimizda> TBL_Hakkimizda { get; set; }
        public virtual DbSet<TBL_Karin> TBL_Karin { get; set; }
        public virtual DbSet<TBL_Kategori> TBL_Kategori { get; set; }
        public virtual DbSet<TBL_Kol> TBL_Kol { get; set; }
        public virtual DbSet<TBL_Omuz> TBL_Omuz { get; set; }
        public virtual DbSet<TBL_Sirt> TBL_Sirt { get; set; }
        public virtual DbSet<TBL_Yorumlar> TBL_Yorumlar { get; set; }
    }
}
