//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YapayAntenor.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class TBL_Omuz
    {
        public int OmuzID { get; set; }
        public string OmuzReism { get; set; }
        public string OmuzHareket { get; set; }
        [AllowHtml]
        public string OmuzAciklama { get; set; }
    }
}
