//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YapayAntenor.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Yorumlar
    {
        public int YorumID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Mail { get; set; }
        public string Yorum { get; set; }
        public Nullable<int> Blog { get; set; }
        public Nullable<int> Beslenme { get; set; }
    
        public virtual TBL_Blog TBL_Blog { get; set; }
        public virtual TBL_Beslenme TBL_Beslenme { get; set; }
    }
}
