//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YapayAntenor.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;    
    using System.Web.Mvc;

    public partial class TBL_Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Blog()
        {
            this.TBL_Yorumlar = new HashSet<TBL_Yorumlar>();
        }

        public int BlogID { get; set; }
        public string BlogBaslik { get; set; }

        
        public Nullable<System.DateTime> BlogTarih { get; set; }
        [AllowHtml]
        public string BlogAciklama { get; set; }
        public Nullable<int> BlogYazar { get; set; }
        public string BlogImage { get; set; }
        public Nullable<int> BlogKategori { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TBL_Admin TBL_Admin { get; set; }
        public virtual TBL_Kategori TBL_Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Yorumlar> TBL_Yorumlar { get; set; }
    }
}
