//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YapayAntenor.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class TBL_Beslenme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Beslenme()
        {
            this.TBL_Yorumlar = new HashSet<TBL_Yorumlar>();
        }
    
        public int BeslenmeID { get; set; }
        public string BeslenmeBaslik { get; set; }
        public string BeslenmeResim { get; set; }
        public Nullable<System.DateTime> BeslenmeTarih { get; set; }
        public Nullable<int> BeslenmeYazar { get; set; }
        [AllowHtml]
        public string BeslenmeAciklama { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TBL_Admin TBL_Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Yorumlar> TBL_Yorumlar { get; set; }
    }
}
